from django.urls import path
from rest_framework.authtoken.views import  obtain_auth_token

from myapp.views import(
    homepage,
    account_verification,
    main_portal,
    resend_otp,
    simple_login,
    voter,
    create_user,
    vote_casting,
    watch_video,
    contact_page,
    complete,
    ecp_overview,
    registration,
    verify_registration,
    check_registration,
    detail,
    main_user_create,
    Home_api,
    party,
    party_1,
    vote,
    home_id,
    introduction,Voter_instructions,
    video_function,logout_main,front_page,
    general_election,create_user,user_profile
    )
urlpatterns = [
    path('front_page/',front_page,name='front-page'),
    path('ECP/',homepage),
    path('cast_vote/<int:id>/',vote_casting),
    path('cast_vote/<int:id>/send_detail/',detail),
    path('front_page/login/',simple_login),
    path('front_page/Account_verification/',account_verification),
    path('front_page/login/send_detail/',detail),
    path('front_page/login/home_page/',homepage),
    path('front_page/login_verification/',create_user),
    path('verify_registration/',verify_registration),
    path('verify_registration/ECP_overview/',ecp_overview),
    path('verify_registration/registration/',registration),
    # path('verify_registration/verify_registration/',double_verification),
    path('registration/',registration),
    path('ECP_overview/',ecp_overview),
    path('front_page/login_verification/Admin/complete_data/',complete),
    path('contact/',contact_page),
    path('watch_video/',watch_video),
    path('front_page/Account_verification/main_portal/cast_vote/<int:id>/',vote_casting,name="vote-casting"),
    path('front_page/Account_verification/main_portal/cast_vote/<int:id>/send_detail/',detail),
    path('front_page/Account_verification/otp_reverification/',resend_otp),
    path('front_page/Account_verification/main_portal/',main_portal,name="my_portal"),
    path('login/',simple_login),
    path('login/main_portal/',main_portal),
    path('Admin/',voter),
    path('login/main_portal/cast_vote/<int:id>/',vote_casting),
    path('login/main_portal/cast_vote/send_detail/',detail),
    path('login/send_detail/',detail),
    path('Admin/',voter,name='user-reverse'),
    path('Admin/upload_video/',video_function),
    path('Admin/user_create/',main_user_create),
    path('Admin/check_registration/',check_registration),
    path('general_election/',general_election),
    path('logout/',logout_main),
    path('Admin/logout/',logout_main),
    path('for_voter/',Voter_instructions),
    path('user_profile/',user_profile),
    # Api 
    path('home/',Home_api),
    path('home/<int:id>/',home_id),
    path('party/<int:id>/',party),
    path('party_all/',party_1),
    path('vote_casting/',vote),
    path('intro/',introduction),
    path('authhhh/',obtain_auth_token,name='auth')
]
 