# Generated by Django 5.0.2 on 2024-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election_introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_flag', models.ImageField(upload_to='voter_panel')),
                ('party_name', models.CharField(max_length=100)),
                ('party_symbol', models.ImageField(upload_to='party_symbols')),
                ('candidate_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('email_adress', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Party1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Id_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='Vote_casting',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(default='', max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('party', models.CharField(max_length=40)),
                ('id_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
