# Generated by Django 5.0.4 on 2024-06-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election_introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_flag', models.ImageField(upload_to='voter_panel')),
                ('party_name', models.CharField(max_length=100)),
                ('party_symbol', models.ImageField(upload_to='candidate_image')),
                ('candidate_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='party_symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_adress', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Party1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Id_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='Vote_casting',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(default='', max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('party', models.CharField(max_length=40)),
                ('id_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
