# Generated by Django 5.0.2 on 2024-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='id',
        ),
        migrations.AlterField(
            model_name='home',
            name='id_no',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
