# Generated by Django 5.0.2 on 2024-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cnic',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
