# Generated by Django 5.0.2 on 2024-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userprofile_id_alter_userprofile_cnic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='father_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='home',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
